### ISSUE TITLE
Problem with injections

### ISSUE THREAD

**Issue by pabloalcaraz** [njleonzhang/generator-gulp-ionic#10]
Hi,

I want to separato my files of each page on (for example):
main-module.js
```
'use strict';
      angular.module('app.main', ['ionic']);
```
main-controller.js
```
'use strict';
angular.module('app.main')
  .controller('mainCtrl', () => {});
```
main-states.js
```
'use strict';
angular.module('app.main')
  .config(($stateProvider) => {
    // Application routing
    $stateProvider
      .state('main', {
        url: '/main',
        templateUrl: 'src/pages/main/main.html',
        controller: 'mainCtrl'
      });
  });
```
main.html

and my app.js

```
'use strict';
angular.module('app', [
    'ionic',
    'ngAnimate',
    'ngCordova',
    'ENV',
    'app.main'
  ])
  .run(($ionicPlatform) => {
    $ionicPlatform.ready(() => {
      // save to use plugins here
    });
    // add possible global event handlers here
  })
  // config
  .config(($urlRouterProvider) => {
    // redirects to default route for undefined routes
    $urlRouterProvider.otherwise('/main');
  });
```

But the injections fails and I don't know why, but angular doesn't find the modules.

Thanks.

**Comment by njleonzhang** [comment]
which `injection` fails?
you can generate a page use `yo gulp-ionic:page [name]`, which will generate js, css and html for you.

**Comment by pabloalcaraz** [comment]
app.main on main-controller.js not found, says that app.main is not injected.

Yes I know, but I want to separate the js in differente files -states, -controller, and -module. 

I will try it to test it but I don't know why is failing.

**Comment by njleonzhang** [comment]
OK, so what you are talking about should be a question on Angular1.
To be honest, I have not worked on Angular1 for a long time, so I am not familiar to the syntax now. I can not help you with this code fragment. I suggest you to debug with someone who is currently working on Angular1. :-)
