### ISSUE TITLE
ionic directive style cant apply

### ISSUE THREAD

**Issue by jackhu1990** [njleonzhang/generator-gulp-ionic#7]
hi, thanks for your job!
when i use [ion-datetime-picker](https://github.com/katemihalikova/ion-datetime-picker)
I find the style cant be applied. 
before i use yo, i add something  to my index.html usually.
like this: 
```
<script src="lib/ion-datetime-picker/release/ion-datetime-picker.min.js"></script>
<link href="lib/ion-datetime-picker/release/ion-datetime-picker.min.css" rel="stylesheet">
```
what can i do for generator-gulp-ionic? plese help me.

**Comment by jackhu1990** [comment]
1st is used generator-gulp-ionic. 2nd is my olded project.
![image](https://cloud.githubusercontent.com/assets/9961996/21513334/2629979e-ccf2-11e6-9104-8d5fd4b63312.png)
![image](https://cloud.githubusercontent.com/assets/9961996/21513371/76517b4c-ccf2-11e6-84e5-f82b0f2c1275.png)

**Comment by njleonzhang** [comment]
看起来样式生效了，是有冲突  你具体看下怎么冲突了。
设计上来说，第三方库是用bower 管理的。

```
bower install ion-datetime-picker --save
```

但是他这个库做的不太好，没有将css和js bundle在一起。
所以你可能需要自己引入一下css。

用类似的方法，路径可以先按照你的路径先写死，这样讲究着能用。。。
```
<link href="lib/ion-datetime-picker/release/ion-datetime-picker.min.css" rel="stylesheet">
```

或者更简单一点，你把他代码拷到你项目里当做一个directive。。。。。

================

我做的时候好像有考虑这种场景（第3方库没有bundle的场景），我现在想不起来怎么配置了。我晚点看下。

**Comment by jackhu1990** [comment]
问题解决了。我在ionic-style中参考你引入ionic样式的方式引入的指令的样式。
```
@import "bower_components/ion-datetime-picker/src/picker";

```
非常感谢。

**Comment by njleonzhang** [comment]
恩，这样也行，相当于把问题绕过去了。。。你好机智，哈哈。用的爽的话给个star吧。:-)
