### ISSUE TITLE
Bower packages not wired into source code

### ISSUE THREAD

**Issue by ghost** [njleonzhang/generator-gulp-ionic#8]
@njleonzhang this generator has streamlined soooo much for me and it's awesome!

I'm just having troubles wrapping my head around why certain bower components don't get wired into the build? Example: https://github.com/jirikavi/AngularJS-Toaster

I install the bower package and for the life of me can't get it included in the index.html file... Am I missing something? ngMap works fine (https://github.com/allenhwkim/angularjs-google-maps) but when I try the toastr package it's not included in the source and I'm thrown an error that angular is not installed.

I'm banging my head against the wall and would appreciate any feedback you have.

Thanks brother!

**Comment by njleonzhang** [comment]
@spencerspear I am so happy that this project can help you. I will help to check this issue, it may cost some time. You can also check the gulpfile to debug it by yourself.

**Comment by njleonzhang** [comment]
@spencerspear 
Add the following to bower.json: 
```
"AngularJS-Toaster": {
      "dependencies": {}
    }
```

sample: 
```
{
  "name": "gulpIonic",
  "author": "njleonzhang <scream3616@sina.com>",
  "private": "true",
  "devDependencies": {},
  "dependencies": {
    "ionic": "1.3.1",
    "ngCordova": "0.1.27-alpha",
    "AngularJS-Toaster": "angularjs-toaster#^2.1.0"
  },
  "overrides": {
    "ionic": {
      "main": "release/js/ionic.bundle.js",
      "dependencies": {}
    },
    "ngCordova": {
      "dependencies": {}
    },
    "AngularJS-Toaster": {
      "dependencies": {}
    }
  }
}
```

so why?
Look at `AngularJS-Toaster`'s bower.json
```
{
  "name": "AngularJS-Toaster",
  "version": "2.0.0",
  "main": [
    "toaster.js",
    "toaster.css",
    "toaster.scss"
  ],
  "ignore": [
    "**/.*",
    "node_modules",
    "components"
  ],
  "dependencies": {
    "angular": ">1.2.6",
    "angular-animate": ">1.2.8"
  }
}
```
`AngularJS-Toaster` exports  `["toaster.js", "toaster.css", "toaster.scss"]` by `main`, and depends on `["angular": ">1.2.6", "angular-animate": ">1.2.8"]`.  

`gulp-ionic` injects the dependency by `wiredep`.  `wiredep` will parse `bower.json` files of all the libraries you described in your `bower.json`. It check if all dependencies are ready, if not, an exception will be throw. so this is why you see the following exception:

```
/Users/leon/Documents/localCode/gulp-ionic/node_modules/.3.0.1@wiredep/wiredep.js:30
    ('on-error', opts.onError || function(err) { throw new Error(err); })
                                                 ^

Error: Error: angular is not installed. Try running `bower install` or remove the component from your bower.json file.
    at /Users/leon/Documents/localCode/gulp-ionic/node_modules/.3.0.1@wiredep/wiredep.js:30:56
    ....
```
`AngularJS-Toaster` depends on `angular` and `angular-animate`, but you have not installed `angular`, so it throws exception. (as you know, angular is already bundled in ionic.bundle.js, which we have already injected), so the solution is just ignore the dependency of `AngularJS-Toaster`. 

Bingo!!! In you project's `bower.json`, 
add 
```
    "AngularJS-Toaster": {
      "dependencies": {}
    }
```
under `overrides` to make it. 

:) With this method, you can solve all this kind of issues.


![2017-02-21 1 28 34](https://cloud.githubusercontent.com/assets/13174059/23152018/fd7ccd2a-f839-11e6-8d2e-ff0851641f62.png)

**Comment by ghost** [comment]
Thank you for the detailed explanation Leon! Your help is greatly appreciated.

Keep up the great work!

Regards,

Spencer Spear
spear.spencer@gmail.com
(647) 870-2557

**Comment by njleonzhang** [comment]
close the issue
